replicaCount: 1

image:
  repository: helloWorldBoxboat
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gitlab-nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: INSERT INGRESS PATH
